- aws/terraform_provider.go
- e2e/aws_estimation_test.go
- terraform/plan.go
- terraform/plan_test.go
- terraform/provider.go
- terraform/schema.go
This PR solves two problems:
1. Terraform 0.13 changed the value of `provider_name` field in a resource spec: it is now a fully qualified URI (`registry.terraform.io/hashicorp/aws`) instead of being just a provider name (`aws`). This requires the fully qualified name (`RegistryName`) to be added to the `MatchNames` list of AWS `ProviderInitializer` as well as a change to how plans are read. This closes #18. Note: after the change, multiple aliases for a provider will not work, this will be fixed in a separate issue.
2. Referencing variables in provider config would not work as variables were unsupported. This PR adds support for using variables in provider config and closes #19.
> Fix problems with Terraform 0.13+ and usage of variables

- aws/filter.go
- aws/filter_test.go
- aws/ingester.go
- aws/options.go
WithIngestionFilter option can be used to control the data that is ingested into the database. By using MinimalFilter, only the minimal amount of data is ingested, saving time and storage space.
This PR closes #22.
> aws: add WithIngestionFilter option and implement MinimalFilter

- CONTRIBUTING.md
- Makefile
- docker-compose.yml
- e2e/aws_estimation_test.go
- e2e/aws_ingestion_test.go
- ingestion.go
- scripts/migrate.go
This PR improves end-to-end testing by including a `docker-compose.yml` file and a `Makefile` to easily spin up a local environment.
Related: #21
> Include a DB Docker container and a Makefile

- cost/component.go
- cost/component_test.go
- cost/resource.go
- cost/resource_test.go
- cost/state.go
- cost/state_test.go
- e2e/aws_estimation_test.go
Whenever a `cost.State` is created using `cost.NewState` function, the previous behaviour was to fail it the first time an error is encountered (e.g. when no product matching the query was found.)
This PR adds a new field on `Component` to store the error. It is used by `cost.NewState` instead of returning the error from the function. The errors can then be read from a `ResourceDiff` by using the `Errors` method.
Closes #17
> cost: store the errors instead of failing

- aws/filter.go
- aws/terraform/lb.go
- aws/terraform/lb_test.go
- aws/terraform/provider.go
This PR adds support for the following resources from the `AWSELB` service:
- `aws_elb` - Classic Load Balancer
- `aws_lb`/`aws_alb` - Load Balancer v2
In order to estimate these properly, the `AWSELB` service pricing must be ingested first.
> aws: add support for aws_lb/aws_alb/aws_elb resources

- aws/ingester.go
- aws/ingester_test.go
- aws/services.go
- e2e/aws_ingestion_test.go
This PR adds a list of supported AWS services as well as validates it when creating a new Ingester. This causes a breaking change.
Closes #14
> aws: expose a list of supported services

- e2e/aws_estimation_test.go
- terraform/plan.go
- terraform/plan_test.go
- terraform/schema.go
- testdata/terraform-plan.json
This PR fixes a bug due to which resources wouldn't be correctly estimated if using provider aliases. Closes #31
> terraform: support provider aliases

- cost/plan.go
- cost/plan_test.go
- cost/resource.go
- cost/state.go
- cost/state_test.go
- query/query.go
- terraform/plan.go
- terraform/plan_test.go
- terraform/schema.go
This PR adds a new `Skipped` field to `cost.Resource`, as well as a new `SkippedAddresses` method to `cost.Plan` that returns a list of resource addresses that were skipped in the estimation process. Closes #12
> estimation: expose a list of skipped resources

- cost/component.go
- cost/component_test.go
- cost/cost.go
- cost/cost_test.go
- cost/plan.go
- cost/plan_test.go
- cost/resource.go
- cost/state.go
- cost/state_test.go
- e2e/aws_estimation_test.go
This PR adds a new Cost struct that wraps the Decimal in order to provide `Hourly` and `Monthly` methods returning per-hour and per-month cost of a component or resource.
Closes #33
> cost: return per-hour cost of resources

- CHANGELOG.md
- terraform/plan.go
- terraform/plan_test.go
- terraform/schema.go
- testdata/terraform-plan.json
This PR adds the child module support to the Terraform plan schema. It splits the `Plan.extractQueries` method into two: 
- `extractModuleConfiguration` - fills the `resourceProviders` map by recursively calling itself for each descendant of the root module
- `extractModuleQueries` - returns a list of resource queries by recursively calling itself for each descendant of the root module
Closes #37.
> terraform: add child module support

- CHANGELOG.md
- aws/terraform/provider.go
- cost/plan.go
- cost/resource.go
- cost/state.go
- mock/terraform_provider.go
- query/query.go
- terraform/plan.go
- terraform/plan_test.go
- terraform/provider.go
This PR adds `Provider` and `Type` values to estimated resources. Closes #42
> cost: expose `Provider` and `Type` of resources

- CHANGELOG.md
- cost/cost.go
- cost/resource.go
- cost/resource_test.go
- e2e/aws_estimation_test.go
Fixed issue #51 where prior component cost was used to calculate planned cost for resource diff. Also added tests to cover prior and planned cost calculation for resource diff.
> Correct planned cost calculation for resource diff

- CHANGELOG.md
- go.mod
- terraform/hcl.go
- terraform/hcl_test.go
The resources later converter to components had those fields set, but
the resource itself containing those components were missing it.
> hcl: type/provider were missing for resources

- e2e/aws_estimation_test.go
- terraform/hcl.go
- terraform/provider.go
- testdata/aws/stack-magento/magento.tf
- testdata/aws/stack-magento/module-magento/ami.tf
- testdata/aws/stack-magento/module-magento/front.tf
- testdata/aws/stack-magento/module-magento/iam.tf
- testdata/aws/stack-magento/module-magento/outputs.tf
- testdata/aws/stack-magento/module-magento/rds.tf
- testdata/aws/stack-magento/module-magento/redis.tf
- testdata/aws/stack-magento/module-magento/variables.tf
- testdata/aws/stack-magento/outputs.tf
- testdata/aws/stack-magento/provider.tf
- testdata/aws/stack-magento/versions.tf
If using another provider (e.g. 'random'), the execution would stop because of the recursion of the function, so using the flag logic doesn't work as expected when multiple providers are mixed.
Instead that logic has been extracted afterwards, to ensure that at least one of the queries is of a known provider's type.
Closes: https://github.com/cycloidio/terracost/issues/56
> terraform: fix unexpected error with multiple providers

- CHANGELOG.md
- aws/terraform_provider.go
- e2e/aws_estimation_test.go
- terraform/error.go
- terraform/plan.go
- terraform/provider.go
- testdata/aws/terraform-plan-noprovider.json
Certain providers of Terraform are meant to specify constraint rather
than locations/regions, etc. In cases where a provider doesn't contain a
valid location, it will not be added to the list of valid providers, if
no providers at all exist an error will be returned mentioning it.
> providers: ignore "constraint providers"

- CHANGELOG.md
- e2e/aws_estimation_test.go
- estimation.go
- testdata/aws/terraform-noprior-plan.json
In the case where it's the first time running the plan, there will be no
prior queries/cost to estimate from, as this is now detected, this error
should be ignored to return the appropriate plan cost.
> estimation: return cost when no prior queries found

- CHANGELOG.md
- aws/terraform/autoscaling_group.go
- aws/terraform/db_instance.go
- aws/terraform/eip.go
- aws/terraform/elasticache_cluster.go
- aws/terraform/elasticache_replication_group.go
- aws/terraform/instance.go
- aws/terraform/launch_configuration.go
- aws/terraform/launch_template.go
- aws/terraform/lb.go
- aws/terraform/provider.go
- aws/terraform/volume.go
- azurerm/terraform/linux_virtual_machine.go
- azurerm/terraform/virtual_machine.go
- e2e/aws_estimation_test.go
- estimation.go
- examples/README.md
- examples/terracost.go
- google/terraform/compute_instance.go
- testdata/aws/stack-magento/magento.tf
We used specific typing which when failed to convert ignored the resource price calculation, now we have weak type (`"20"` to `20` for example) which means it's more align with Terraform type system.
> Fixed issue with weak types on user input

- CHANGELOG.md
- aws/terraform_provider.go
- e2e/aws_estimation_test.go
- e2e/invalid_estimation_test.go
- testdata/aws/terraform-plan-no-region.json
This case is when the variable is passed via ENV variables and it's not recorded on the Plan/HCL so we cannot get it by reading neither of those files
> aws: If the AWS provider is defined without a region the 'us-east-1' is used

- CHANGELOG.md
- README.md
- e2e/aws_estimation_test.go
- e2e/azurerm_estimation_test.go
- e2e/gcp_estimation_test.go
- e2e/invalid_estimation_test.go
- estimation.go
- terraform/hcl.go
- terraform/hcl_test.go
- terraform/plan.go
- usage/usage.go
- usage/usage_test.go
This is passed when estimating HCL and Plan so they can be conputed with the rest of the configuration
Closes #96
> usage: Added 'Usage' struct to hold all the supported usage

- CHANGELOG.md
- cost/component.go
- cost/state.go
- query/query.go
So then we can differenciate which Components are from Usage or not
Closes #100
> cost|query: Added the Usate to the Components

- terraform/hcl.go
As the caller assumes the 'dir' retunred is the one used to store the values
> terraform/hcl: The 'dir' on the FS was expected to not be the '' one before

- google/ingester.go
- google/ingester_test.go
- google/terraform_provider.go
- google/zone.go
- google/zone_test.go
Invalid zones will return an error from now on for google ingester
> google: return an error if the zone has invalid format

- CHANGELOG.md
- e2e/aws_estimation_test.go
- terraform/hcl.go
- testdata/aws/stack-functions/main.tf
- testdata/aws/stack-functions/module-ec2/main.tf
So then they can be used and evaluated
Closes #126
> terraform: Load HCL functions into the eval context

- CHANGELOG.md
- aws/terraform_provider.go
- aws/terraform_provider_test.go
Fixed unchecked conversion to string of a potentially nil value.
> aws: fix assigning default region
